export const COUNTRY_NAME_TO_PHONE: Record<string, string> = {
  "united states": "us",
  usa: "us",
  us: "us",
  canada: "ca",
  "united kingdom": "uk",
  uk: "uk",
  "great britain": "uk",
  england: "uk",
  germany: "de",
  france: "fr",
  italy: "it",
  spain: "es",
  ukraine: "ua",
  україна: "ua",
  poland: "pl",
  austria: "at",
  "czech republic": "cz",
  czechia: "cz",
  japan: "jp",
  "south korea": "kr",
  korea: "kr",
  australia: "au",
  "united arab emirates": "ae",
  uae: "ae",
  israel: "il",
  turkey: "tr",
  türkiye: "tr",
};

export const OPTIONAL_SOCIALS = [
  { key: "telegram", label: "Telegram", placeholder: "@Username" },
  { key: "whatsapp", label: "WhatsApp", placeholder: "Phone number" },
  { key: "tiktok", label: "TikTok", placeholder: "https://tiktok.com/@name" },
  {
    key: "facebook",
    label: "Facebook",
    placeholder: "https://facebook.com/page",
  },
  {
    key: "youtube",
    label: "YouTube",
    placeholder: "https://youtube.com/@channel",
  },
] as const;
