// нужно заменить все вхождения из этого файла на импорт типов из @quarry/api-types/aliases, например:
// вместо
// import type { Admin } from "@/shared/types/api";
// нужно писать
// import type { AboutBlock } from "@quarry/api-types/aliases";

export type {
  AboutBlock,
  Admin,
  AnalyticsDashboard,
  AuthContext,
  AuthUser,
  BookingStep,
  Catalog,
  ClientInsightsData,
  CompleteModuleDto,
  CompleteModuleResponse,
  CreateAdminDto,
  CreateBookingStepDto,
  CreateCatalogDto,
  CreateDesignDto,
  CreateEventDto,
  CreateFaqCategoryDto,
  CreateFaqItemDto,
  CreateInquiryDto,
  CreatePortfolioDto,
  CreateReviewDto,
  Design,
  Event,
  FaqCategory,
  FaqItem,
  ImageAttachment,
  Inquiry,
  InquiryStatus,
  MediaUploadResponse,
  OnboardingContext,
  OnboardingNavigation,
  OnboardingNavigationStep,
  Order,
  OrderItem,
  OwnerContext,
  Portfolio,
  ProfileDto,
  ProfileMe,
  PublicOwnerProfile,
  PublicSiteContent,
  PublicSiteResponse,
  PublicSiteSettings,
  PublicSocialMedia,
  ReferralSourceData,
  ResponseSettings,
  Review,
  SiteContext,
  SiteResponse,
  SiteSectionsDto,
  SourceConversionData,
  TrafficSource,
  TrafficSourceCount,
  UpdateAdminDto,
  UpdateBookingStepDto,
  UpdateCatalogDto,
  UpdateDesignDto,
  UpdateEventDto,
  UpdateFaqCategoryDto,
  UpdateFaqItemDto,
  UpdateInquiryDto,
  UpdatePortfolioDto,
  UpdateProfileDto,
  UpdateReviewDto,
  UpdateSettings,
} from "@quarry/api-types/aliases";
